[[constraint]]
  name = "github.com/juju/ratelimit"
  version = "v1.0.1"

[[constraint]]
  name = "github.com/juju/errors"
  revision = "22422dad46e14561a0854ad42497a75af9b61909"

[[constraint]]
  name = "github.com/docker/docker"
  source = "https://github.com/moby/moby"
  revision = "62d80835abe3f7bc54c70f5e7bad638eaf3596be"

[[constraint]]
  name = "github.com/docker/cli"
  version = "v18.09"

[[constraint]]
  name = "github.com/rhysd/go-github-selfupdate"
  revision = "41c1bbb0804a2994dae69502a8c76e7c456ad45e"

[[constraint]]
  name = "github.com/sabhiram/go-gitignore"
  version = "1.0.2"

[[constraint]]
  name = "github.com/daviddengcn/go-colortext"
  revision = "186a3d44e9200d7eb331356ca4864f52708e1399"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/otiai10/copy"
  revision = "7e9a647135a142c2669943d4a4d29be015ce9392"

[[constraint]]
  name = "github.com/rjeczalik/notify"
  revision = "629144ba06a1c6af28c1e42c228e3d42594ce081"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "gopkg.in/src-d/enry.v1"
  version = "1.6.4"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.5.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "k8s.io/helm"
  version = "v2.12.0"

[[constraint]]
  name = "github.com/foomo/htpasswd"
  revision = "cb63c4ac0e5029b961b3ac7dcc281ed2a9232e4e"

[[constraint]]
  name = "github.com/bmatcuk/doublestar"
  version = "1.1.1"

[[constraint]]
  name = "github.com/badgerodon/penv"
  revision = "7a4c6d64fa119b52afe2eb3f0801886bd8785318"

[[override]]  
 name = "github.com/prometheus/client_golang"
 version = "0.9.2"

[[override]]
 name = "github.com/docker/go-metrics"
 revision = "399ea8c73916000c64c2c76e8da00ca82f8387ab"

[[override]]
  name = "k8s.io/client-go"
  version = "v10.0.0"

[[override]]
  name = "k8s.io/kubernetes"
  revision = "ddf47ac13c1a9483ea035a79cd7c10005ff21a6d"

[[override]]
  name = "k8s.io/api"
  revision = "89a74a8d264df0e993299876a8cde88379b940ee"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "2b1284ed4c93a43499e781493253e2ac5959c4fd"

[[override]]
  name = "k8s.io/apiserver"
  revision = "9caa0299108fbdf51d3d9b8e8956834ae84dac75"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  revision = "20c909e7c8c3fec1a0e345b1d4e57f1c1623c368"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "v1.5.1"

[[override]]
  name = "github.com/docker/distribution"
  revision = "83389a148052d74ac602f5f1d62f86ff2f3c4aa5"

[[override]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.6"

[[override]]
  name = "github.com/Nvveen/Gotty"
  source = "https://github.com/ijc25/Gotty.git"
  revision = "a8b993ba6abdb0e0c12b0125c603323a71c7790c"

[prune]
  go-tests = true
  unused-packages = true
